import type { Practitioner, DinacharTask, HealthRecord } from "./types";

export const DISCIPLINES = [
  {
    id: "Ayurveda",
    label: "Ayurveda",
    icon: "🌿",
    tagline: "Herbal remedies & body constitution balance",
    color: "oklch(0.29 0.09 158)",
    bg: "bg-emerald-50",
    count: "1,240+",
  },
  {
    id: "Yoga",
    label: "Yoga",
    icon: "🧘",
    tagline: "Therapeutic yoga & pranayama sessions",
    color: "oklch(0.52 0.06 158)",
    bg: "bg-teal-50",
    count: "830+",
  },
  {
    id: "Naturopathy",
    label: "Naturopathy",
    icon: "☀️",
    tagline: "Natural healing & lifestyle correction",
    color: "oklch(0.78 0.12 87)",
    bg: "bg-amber-50",
    count: "460+",
  },
  {
    id: "Unani",
    label: "Unani",
    icon: "⚗️",
    tagline: "Greco-Arabic medicine & humoral balance",
    color: "oklch(0.64 0.10 43)",
    bg: "bg-orange-50",
    count: "310+",
  },
  {
    id: "Siddha",
    label: "Siddha",
    icon: "🔮",
    tagline: "South Indian classical medicine tradition",
    color: "oklch(0.48 0.07 280)",
    bg: "bg-purple-50",
    count: "220+",
  },
  {
    id: "Homeopathy",
    label: "Homeopathy",
    icon: "💧",
    tagline: "Potentised micro-dose remedies",
    color: "oklch(0.48 0.09 220)",
    bg: "bg-blue-50",
    count: "680+",
  },
] as const;

export const MOCK_PRACTITIONERS: Practitioner[] = [
  {
    id: "doc-001",
    name: "Dr. Aditi Shastri",
    specialty: "Panchakarma & Chronic Joint Care",
    discipline: "Ayurveda",
    experience: 15,
    rating: 4.9,
    reviews: 1284,
    fee: 699,
    hprId: "HPR-4902-8822",
    isVerified: true,
    avatar: "AS",
    languages: ["English", "Hindi", "Kannada"],
    consultModes: ["video", "clinic"],
    nextAvailable: "Today, 4:30 PM",
    location: "Indiranagar, Bangalore",
    qualifications: ["BAMS", "MD Ayurveda", "PG Panchakarma"],
    about:
      "Senior Ayurvedic Physician specialising in Panchakarma detoxification and chronic joint management. Combines classical Ayurvedic methodology with evidence-informed clinical practice.",
  },
  {
    id: "doc-002",
    name: "Dr. Ramesh Iyer",
    specialty: "Digestive Disorders & Metabolism",
    discipline: "Ayurveda",
    experience: 11,
    rating: 4.7,
    reviews: 876,
    fee: 499,
    hprId: "HPR-3712-5500",
    isVerified: true,
    avatar: "RI",
    languages: ["English", "Tamil", "Telugu"],
    consultModes: ["video"],
    nextAvailable: "Tomorrow, 10:00 AM",
    location: "T. Nagar, Chennai",
    qualifications: ["BAMS", "PG Kaya Chikitsa"],
    about:
      "Specialising in Agni (digestive fire) restoration, Agnimandya management, and metabolic correction through classical herbal formulations.",
  },
  {
    id: "doc-003",
    name: "Dr. Farah Khan",
    specialty: "Unani Internal Medicine",
    discipline: "Unani",
    experience: 9,
    rating: 4.8,
    reviews: 542,
    fee: 599,
    hprId: "HPR-6601-2290",
    isVerified: true,
    avatar: "FK",
    languages: ["English", "Urdu", "Hindi"],
    consultModes: ["video", "clinic"],
    nextAvailable: "Today, 6:00 PM",
    location: "Old Delhi",
    qualifications: ["BUMS", "MD Unani Medicine"],
    about:
      "Expert in Mizaj-based diagnosis and humoral balance correction through Unani pharmacopoeia including Majoon, Sharbat, and Khamira formulations.",
  },
  {
    id: "doc-004",
    name: "Dr. Priya Menon",
    specialty: "Yoga Therapy & Spine Rehabilitation",
    discipline: "Yoga",
    experience: 7,
    rating: 4.9,
    reviews: 398,
    fee: 399,
    hprId: "HPR-8810-4430",
    isVerified: true,
    avatar: "PM",
    languages: ["English", "Malayalam", "Tamil"],
    consultModes: ["video"],
    nextAvailable: "Today, 5:00 PM",
    location: "Kozhikode, Kerala",
    qualifications: ["BSc Yoga", "PGDY", "PGDYT"],
    about:
      "Certified therapeutic yoga specialist offering evidence-based yoga protocols for spinal disorders, stress management, and chronic pain rehabilitation.",
  },
];

export const MOCK_DINACHAR_TASKS: DinacharTask[] = [
  {
    id: "t1",
    time: "06:00 AM",
    title: "Oil Pulling (Kavala)",
    description: "Swish 1 tbsp sesame oil for 10–15 mins",
    done: true,
    category: "mindfulness",
  },
  {
    id: "t2",
    time: "06:30 AM",
    title: "Warm Water with Lemon",
    description: "Ignite digestive fire (Agni)",
    done: true,
    category: "diet",
  },
  {
    id: "t3",
    time: "07:00 AM",
    title: "Pranayama — 15 mins",
    description: "Nadi Shodhana & Bhramari breathing",
    done: false,
    category: "exercise",
  },
  {
    id: "t4",
    time: "08:00 AM",
    title: "Morning Medication",
    description: "Ashwagandha Churna — 1 tsp with warm milk",
    done: false,
    category: "medicine",
  },
  {
    id: "t5",
    time: "01:00 PM",
    title: "Sattvic Lunch",
    description: "Light Pitta-balancing meal, avoid raw foods",
    done: false,
    category: "diet",
  },
  {
    id: "t6",
    time: "08:00 PM",
    title: "Evening Medication",
    description: "Triphala — 1 tsp with warm water",
    done: false,
    category: "medicine",
  },
];

export const MOCK_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: "r1",
    date: "2024-05-28",
    type: "consultation",
    title: "Ayurveda Consultation",
    doctor: "Dr. Aditi Shastri",
    discipline: "Ayurveda",
    summary: "Vata-Pitta imbalance. Prescribed Ashwagandha & Triphala regimen.",
  },
  {
    id: "r2",
    date: "2024-05-28",
    type: "prescription",
    title: "Digital Prescription",
    doctor: "Dr. Aditi Shastri",
    discipline: "Ayurveda",
    summary: "Ashwagandha Churna · Triphala Churna · Brahmi Ghee",
  },
  {
    id: "r3",
    date: "2024-04-15",
    type: "consultation",
    title: "Yoga Therapy Session",
    doctor: "Dr. Priya Menon",
    discipline: "Yoga",
    summary: "Spine protocol initiated. 3-month corrective yoga plan created.",
  },
  {
    id: "r4",
    date: "2024-03-10",
    type: "lab",
    title: "Prakriti Assessment",
    discipline: "Ayurveda",
    summary: "Prakriti: Vata-Pitta dominant. Recommendations documented.",
  },
  {
    id: "r5",
    date: "2024-02-20",
    type: "tracker",
    title: "Digestion Tracking Report",
    summary: "30-day tracking: Bloating reduced by 68%. Energy improved.",
  },
];
