import { ROLES, Role } from "./roles";
import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS), // all permissions
  
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_DELETE,
    PERMISSIONS.BOOKING_READ, PERMISSIONS.BOOKING_UPDATE, PERMISSIONS.BOOKING_DELETE,
    PERMISSIONS.RECORDS_READ, PERMISSIONS.RECORDS_UPDATE, PERMISSIONS.RECORDS_DELETE,
    PERMISSIONS.PRESCRIPTION_READ, PERMISSIONS.PRESCRIPTION_UPDATE, PERMISSIONS.PRESCRIPTION_DELETE,
    PERMISSIONS.CONSULTATION_READ, PERMISSIONS.CONSULTATION_UPDATE, PERMISSIONS.CONSULTATION_DELETE, PERMISSIONS.CONSULTATION_PDF,
    PERMISSIONS.MESSAGES_READ, PERMISSIONS.MESSAGES_UPDATE, PERMISSIONS.MESSAGES_DELETE,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_UPDATE, PERMISSIONS.ORDERS_DELETE,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.DOCTOR_READ, PERMISSIONS.DOCTOR_UPDATE,
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE, PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.PRO_ACCESS,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.CONSULTATION_READ, PERMISSIONS.CONSULTATION_CREATE, PERMISSIONS.CONSULTATION_UPDATE, PERMISSIONS.CONSULTATION_PDF,
    PERMISSIONS.PRESCRIPTION_READ, PERMISSIONS.PRESCRIPTION_CREATE, PERMISSIONS.PRESCRIPTION_UPDATE,
    PERMISSIONS.RECORDS_READ, PERMISSIONS.RECORDS_UPDATE,
    PERMISSIONS.MESSAGES_READ, PERMISSIONS.MESSAGES_CREATE,
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE,
  ],

  [ROLES.PATIENT]: [
    PERMISSIONS.PROFILE_READ, PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.BOOKING_READ, PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.CONSULTATION_READ, PERMISSIONS.CONSULTATION_PDF,
    PERMISSIONS.MESSAGES_READ, PERMISSIONS.MESSAGES_CREATE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE,
    PERMISSIONS.CHECKOUT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.AI_CHAT_USE,
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.ADMIN_ACCESS, // Limited dashboard access
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.BOOKING_READ, PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE,
  ],

  [ROLES.PHARMACY]: [
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.ORDERS_READ, PERMISSIONS.ORDERS_UPDATE,
  ],

  [ROLES.GUEST]: [
    // Extremely limited public permissions
  ],
};
